;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsList]
+GameplayTagList=(Tag="Status.Debuff.Burn",         DevComment="燒傷")
+GameplayTagList=(Tag="Status.Debuff.Suffocation",   DevComment="窒息")
+GameplayTagList=(Tag="Status.Debuff.Wet",           DevComment="潮濕")
+GameplayTagList=(Tag="Status.Debuff.Frost",         DevComment="凍傷")
+GameplayTagList=(Tag="Status.Debuff.Frozen",        DevComment="結凍")
+GameplayTagList=(Tag="Status.Debuff.Poison",        DevComment="中毒")
+GameplayTagList=(Tag="Status.Debuff.DarkErosion",   DevComment="暗蝕")
+GameplayTagList=(Tag="Status.Debuff.InstantDeath",  DevComment="即死")
+GameplayTagList=(Tag="Status.Debuff.Paralysis",     DevComment="麻痺")
+GameplayTagList=(Tag="Status.Debuff.EnergySeal",    DevComment="能量封印")
+GameplayTagList=(Tag="Status.Debuff.SkillSeal",     DevComment="封技")
+GameplayTagList=(Tag="Status.Debuff.Bleed",         DevComment="流血")
+GameplayTagList=(Tag="Status.Debuff.Petrify",       DevComment="石化")
+GameplayTagList=(Tag="Status.Debuff.Stun",          DevComment="暈眩")
+GameplayTagList=(Tag="Status.Debuff.Cripple",       DevComment="癱瘓")
+GameplayTagList=(Tag="Status.Debuff.Fear",          DevComment="恐懼")
+GameplayTagList=(Tag="Status.Debuff.Terror",        DevComment="極度恐懼")
+GameplayTagList=(Tag="Status.Debuff.Misfortune",    DevComment="噩運")
+GameplayTagList=(Tag="Status.Debuff.MiningFatigue", DevComment="採掘疲勞")
+GameplayTagList=(Tag="Status.Buff.SuperArmor",      DevComment="霸體")
+GameplayTagList=(Tag="Status.Buff.Phase",           DevComment="虛化")
+GameplayTagList=(Tag="Status.Buff.Invincible",      DevComment="無敵")
+GameplayTagList=(Tag="Status.Buff.ElemResBasic",    DevComment="基礎元素抵抗")
+GameplayTagList=(Tag="Status.Buff.ElemResAdvanced", DevComment="進階元素抵抗")
+GameplayTagList=(Tag="Immunity.Status.Frozen",      DevComment="結凍免疫冷卻")
+GameplayTagList=(Tag="Immunity.Status.Fear",        DevComment="恐懼免疫")
+GameplayTagList=(Tag="Trait.Creature.Beast",        DevComment="野獸類生物")
+GameplayTagList=(Tag="Trait.Creature.NPC",          DevComment="NPC")
+GameplayTagList=(Tag="Trait.Creature.Player",       DevComment="玩家")
+GameplayTagList=(Tag="Trait.Element.Fire",          DevComment="火屬性實體")
+GameplayTagList=(Tag="Trait.Element.Ice",           DevComment="冰屬性實體")

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Status.Buff.ElemResAdvanced",DevComment="")
+GameplayTagList=(Tag="Status.Buff.ElemResBasic",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Invincible",DevComment="")
+GameplayTagList=(Tag="Status.Buff.Phase",DevComment="")
+GameplayTagList=(Tag="Status.Buff.SuperArmor",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Bleed",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Burn",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Cripple",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.DarkErosion",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.EnergySeal",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Fear",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Frost",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Frozen",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.InstantDeath",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.MiningFatigue",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Misfortune",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Paralysis",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Petrify",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Poison",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.SkillSeal",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Suffocation",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Terror",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Wet",DevComment="")

