# split-docs.ps1
# One-time migration: splits PLAN.md and the progress file into modular sub-files.
#
# =====================================================================
#  SPLIT LOGIC  (this mapping IS the spec -- change grouping here)
# =====================================================================
#
#  PLAN.md -> 3 output files
#
#    plan-ability-system.md   sections 1-11
#      "What the ability system IS": design philosophy, totems, containers,
#       engravings, VM blocks, ability points, safety, conflict resolution.
#      Add here when: defining how the ability system itself works.
#
#    plan-references.md       section 12  +  sections 17 through 17-E
#      "What we studied": Noita/Psi/Scratch analysis, external game research.
#      Add here when: adding reference game analysis or inspiration sources.
#
#    plan-roadmap.md          sections 13-16 + section 18 + appendices
#      "How we build it": UI direction, tech choices, impl order, future, glossary.
#      Add here when: updating implementation plan, schedule, or tech decisions.
#
#  Progress file -> 2 outputs
#
#    history/phase1-2.md      Completed Phase 1+2 detail (archive, rarely read)
#    [root file kept slim]    Phase 3 backlog + tech debt (current)
#
# =====================================================================
#  Usage (run from skill-creator root):
#    .\docs\split-docs.ps1
#
#  Overwrites docs/*.md but does NOT modify root .md files.
#  After running, manually rewrite PLAN.md and the progress file as slim indexes.
# =====================================================================

param([string]$Root = (Split-Path $PSScriptRoot -Parent))
Set-Location $Root
New-Item -ItemType Directory -Force -Path ".\docs\history" | Out-Null

# Find first line matching a pattern; return -1 if not found
function Find-Line([string[]]$arr, [string]$pat) {
    for ($i = 0; $i -lt $arr.Count; $i++) {
        if ($arr[$i] -match $pat) { return [int]$i }
    }
    return [int]-1
}

$HDR = @(
    "<!-- Generated by docs/split-docs.ps1 from PLAN.md -->",
    "<!-- Edit this file directly after migration; do not re-run the script. -->",
    ""
)

# ---- PLAN.md -------------------------------------------------------

$plan = Get-Content ".\PLAN.md" -Encoding UTF8

$l1   = [int](Find-Line $plan "^## 1[\.\s]")
$l12  = [int](Find-Line $plan "^## 12[\.\s]")
$l13  = [int](Find-Line $plan "^## 13[\.\s]")
$l17  = [int](Find-Line $plan "^## 17[\.\s]")
$l18  = [int](Find-Line $plan "^## 18[\.\s]")
$last = [int]($plan.Count - 1)

Write-Host ("Boundaries -- 1:{0}  12:{1}  13:{2}  17:{3}  18:{4}  last:{5}" -f `
    $l1,$l12,$l13,$l17,$l18,$last)
Write-Host ""
Write-Host "=== Splitting PLAN.md ===" -ForegroundColor Yellow

# plan-ability-system.md : sections 1-11  (l1 .. l12-1)
$e1 = $l12 - 1
$out = New-Object System.Collections.Generic.List[string]
foreach ($h in $HDR) { $out.Add($h) }
foreach ($ln in $plan[$l1..$e1]) { $out.Add($ln) }
$out | Set-Content ".\docs\plan-ability-system.md" -Encoding UTF8
Write-Host ("  plan-ability-system.md  ({0} lines)" -f $out.Count) -ForegroundColor Cyan

# plan-references.md : §12 (l12..l13-1)  +  §17-17E (l17..l18-1)
$e12 = $l13 - 1
$e17 = $l18 - 1
$out = New-Object System.Collections.Generic.List[string]
foreach ($h in $HDR) { $out.Add($h) }
foreach ($ln in $plan[$l12..$e12]) { $out.Add($ln) }
foreach ($ln in $plan[$l17..$e17]) { $out.Add($ln) }
$out | Set-Content ".\docs\plan-references.md" -Encoding UTF8
Write-Host ("  plan-references.md      ({0} lines)" -f $out.Count) -ForegroundColor Cyan

# plan-roadmap.md : §13-16 (l13..l17-1)  +  §18+appendices (l18..last)
$e13 = $l17 - 1
$out = New-Object System.Collections.Generic.List[string]
foreach ($h in $HDR) { $out.Add($h) }
foreach ($ln in $plan[$l13..$e13]) { $out.Add($ln) }
foreach ($ln in $plan[$l18..$last]) { $out.Add($ln) }
$out | Set-Content ".\docs\plan-roadmap.md" -Encoding UTF8
Write-Host ("  plan-roadmap.md         ({0} lines)" -f $out.Count) -ForegroundColor Cyan

# ---- progress file -------------------------------------------------

Write-Host ""
Write-Host "=== Splitting progress file ===" -ForegroundColor Yellow

$progFile = Get-ChildItem "." -Filter "*.md" -Depth 0 |
    Where-Object { $_.Name -ne "PLAN.md" } |
    Select-Object -First 1

if (-not $progFile) {
    Write-Warning "No root .md file other than PLAN.md found -- skipping."
} else {
    Write-Host "  Source: $($progFile.Name)"
    $prog = Get-Content $progFile.FullName -Encoding UTF8

    $phase3 = [int](Find-Line $prog "^## Phase 3")
    if ($phase3 -lt 0) {
        Write-Warning "  '## Phase 3' not found -- skipping progress split."
    } else {
        # Skip header block (lines 0-9), archive lines 10 .. phase3-1
        $hEnd = $phase3 - 1
        $HIST_HDR = @(
            "<!-- Phase 1 and Phase 2 completed details, archived by split-docs.ps1 -->",
            "<!-- Current status: see root progress file -->",
            ""
        )
        $out = New-Object System.Collections.Generic.List[string]
        foreach ($h in $HIST_HDR) { $out.Add($h) }
        foreach ($ln in $prog[10..$hEnd]) { $out.Add($ln) }
        $out | Set-Content ".\docs\history\phase1-2.md" -Encoding UTF8
        Write-Host ("  history/phase1-2.md     ({0} lines)" -f $out.Count) -ForegroundColor Cyan
        Write-Host "  Phase 3 + tech-debt stays in root file (slim it manually)." -ForegroundColor Yellow
    }
}

# ---- summary -------------------------------------------------------
Write-Host ""
Write-Host "=== Output sizes ===" -ForegroundColor Yellow
Get-ChildItem ".\docs" -Filter "*.md" -Recurse | ForEach-Object {
    [PSCustomObject]@{ File = $_.Name; Lines = (Get-Content $_.FullName).Count }
} | Sort-Object Lines -Descending | Format-Table -AutoSize
Write-Host "Done." -ForegroundColor Green
